sudo: required 
language: generic 
services:
  - docker

before_install: 
  - docker build -t dsaenzjhc/docker-react -f Dockerfile.dev .

Script:
  - docker run dsaenzjhc/docker-react npm run test -- --coverage
